/**
 * The single reducer for all app data.
 *
 * It is deliberately pure — ids and timestamps are generated by the caller and
 * arrive inside the action — so every rule here can be unit tested without a
 * React tree or a device.
 */

import { postDueTransactions } from '../lib/recurring.ts';
import { today, type ISODate } from '../lib/dates.ts';
import type {
  AppData,
  Budget,
  Category,
  Goal,
  GoalContribution,
  RateTable,
  RecurringRule,
  Settings,
  Transaction,
} from '../types.ts';

export type Action =
  | { type: 'hydrate'; data: AppData }
  | { type: 'replaceAll'; data: AppData }
  | { type: 'transaction/add'; transaction: Transaction }
  | { type: 'transaction/update'; transaction: Transaction }
  | { type: 'transaction/delete'; id: string }
  | { type: 'category/add'; category: Category }
  | { type: 'category/update'; category: Category }
  | { type: 'category/delete'; id: string; reassignTo?: string }
  | { type: 'budget/set'; budget: Budget }
  | { type: 'budget/clear'; categoryId: string; month: string | null }
  | { type: 'recurring/add'; rule: RecurringRule }
  | { type: 'recurring/update'; rule: RecurringRule }
  | { type: 'recurring/delete'; id: string }
  | { type: 'recurring/post'; ruleId: string; date: ISODate; transaction: Transaction }
  | { type: 'recurring/skip'; ruleId: string; date: ISODate }
  | { type: 'recurring/runAutoPost'; asOf: ISODate; makeId: () => string; now: string }
  | { type: 'goal/add'; goal: Goal }
  | { type: 'goal/update'; goal: Goal }
  | { type: 'goal/delete'; id: string }
  | { type: 'goal/contribute'; goalId: string; contribution: GoalContribution }
  | { type: 'goal/removeContribution'; goalId: string; contributionId: string }
  | { type: 'settings/update'; patch: Partial<Settings> }
  | { type: 'rates/set'; table: RateTable };

function replaceById<T extends { id: string }>(items: T[], next: T): T[] {
  let found = false;
  const result = items.map((item) => {
    if (item.id !== next.id) return item;
    found = true;
    return next;
  });
  return found ? result : [...result, next];
}

export function reducer(state: AppData, action: Action): AppData {
  switch (action.type) {
    case 'hydrate':
    case 'replaceAll':
      return action.data;

    case 'transaction/add':
      return { ...state, transactions: [action.transaction, ...state.transactions] };

    case 'transaction/update':
      return { ...state, transactions: replaceById(state.transactions, action.transaction) };

    case 'transaction/delete':
      return { ...state, transactions: state.transactions.filter((t) => t.id !== action.id) };

    case 'category/add':
      return { ...state, categories: [...state.categories, action.category] };

    case 'category/update':
      return { ...state, categories: replaceById(state.categories, action.category) };

    case 'category/delete': {
      const { id, reassignTo } = action;
      // Deleting a category that is still referenced would orphan rows, so
      // either move them somewhere else or keep the category as archived.
      const referenced =
        state.transactions.some((t) => t.categoryId === id) ||
        state.recurring.some((r) => r.categoryId === id);
      if (referenced && !reassignTo) {
        return {
          ...state,
          categories: state.categories.map((c) => (c.id === id ? { ...c, archived: true } : c)),
        };
      }
      return {
        ...state,
        categories: state.categories.filter((c) => c.id !== id),
        transactions: reassignTo
          ? state.transactions.map((t) => (t.categoryId === id ? { ...t, categoryId: reassignTo } : t))
          : state.transactions,
        recurring: reassignTo
          ? state.recurring.map((r) => (r.categoryId === id ? { ...r, categoryId: reassignTo } : r))
          : state.recurring,
        budgets: state.budgets.filter((b) => b.categoryId !== id),
      };
    }

    case 'budget/set': {
      const { budget } = action;
      const others = state.budgets.filter(
        (b) => !(b.categoryId === budget.categoryId && b.month === budget.month)
      );
      // A zero limit means "no budget", which is cleaner than storing a 0 row.
      return { ...state, budgets: budget.amount > 0 ? [...others, budget] : others };
    }

    case 'budget/clear':
      return {
        ...state,
        budgets: state.budgets.filter(
          (b) => !(b.categoryId === action.categoryId && b.month === action.month)
        ),
      };

    case 'recurring/add':
      return { ...state, recurring: [...state.recurring, action.rule] };

    case 'recurring/update':
      return { ...state, recurring: replaceById(state.recurring, action.rule) };

    case 'recurring/delete':
      return {
        ...state,
        recurring: state.recurring.filter((r) => r.id !== action.id),
        // Rows already written to the ledger stay; they just lose the link.
        transactions: state.transactions.map((t) =>
          t.recurringId === action.id ? { ...t, recurringId: undefined } : t
        ),
      };

    case 'recurring/post':
      return {
        ...state,
        transactions: [action.transaction, ...state.transactions],
        recurring: state.recurring.map((r) =>
          r.id === action.ruleId ? { ...r, lastPostedDate: action.date } : r
        ),
      };

    case 'recurring/skip':
      return {
        ...state,
        recurring: state.recurring.map((r) =>
          r.id === action.ruleId ? { ...r, lastPostedDate: action.date } : r
        ),
      };

    case 'recurring/runAutoPost': {
      const { transactions, rules } = postDueTransactions(
        state.recurring,
        action.asOf,
        action.makeId,
        action.now
      );
      if (transactions.length === 0) return state;
      return {
        ...state,
        transactions: [...transactions.reverse(), ...state.transactions],
        recurring: rules,
      };
    }

    case 'goal/add':
      return { ...state, goals: [...state.goals, action.goal] };

    case 'goal/update':
      return { ...state, goals: replaceById(state.goals, action.goal) };

    case 'goal/delete':
      return { ...state, goals: state.goals.filter((g) => g.id !== action.id) };

    case 'goal/contribute':
      return {
        ...state,
        goals: state.goals.map((g) =>
          g.id === action.goalId
            ? { ...g, contributions: [action.contribution, ...g.contributions] }
            : g
        ),
      };

    case 'goal/removeContribution':
      return {
        ...state,
        goals: state.goals.map((g) =>
          g.id === action.goalId
            ? { ...g, contributions: g.contributions.filter((c) => c.id !== action.contributionId) }
            : g
        ),
      };

    case 'settings/update':
      return { ...state, settings: { ...state.settings, ...action.patch } };

    case 'rates/set':
      return { ...state, rates: action.table };

    default:
      return state;
  }
}

/** Sorted newest first, with a stable tiebreak so lists don't jitter. */
export function sortedTransactions(transactions: Transaction[]): Transaction[] {
  return [...transactions].sort((a, b) => {
    if (a.date !== b.date) return a.date < b.date ? 1 : -1;
    return a.createdAt < b.createdAt ? 1 : a.createdAt > b.createdAt ? -1 : 0;
  });
}

export const todayISO = today;
